name: native_flutter_fonts
description: A Flutter plugin to automatically register Flutter fonts on the native side of Android and iOS.
version: 1.0.1
homepage: https://dra11y.com
repository: https://github.com/dra11y/accessible_text_view

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dra11y.flutter.native_flutter_fonts
        pluginClass: NativeFlutterFontsPlugin
      ios:
        pluginClass: NativeFlutterFontsPlugin
